//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIDMaster
{


    public partial class oid
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HiddenField NodeID;
        protected global::System.Web.UI.WebControls.TextBox txtNotation1;
        protected global::System.Web.UI.WebControls.TextBox txtNotation2;
        protected global::System.Web.UI.WebControls.TextBox txtNotation3;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.TextBox txtOIDInt;
        protected global::System.Web.UI.WebControls.Label lblInformation;
        protected global::System.Web.UI.WebControls.TextBox txtOIDLabel;
        protected global::System.Web.UI.WebControls.TextBox txtOIDSecondary;
        protected global::System.Web.UI.WebControls.TextBox txtUnicodeLabel;
        protected global::System.Web.UI.WebControls.Label lblNodeID;
        protected global::System.Web.UI.WebControls.Label lblRootNode;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divParent;
        
    }
}
